### PR TITLE
Add Whonix 16 configs

### PR DESCRIPTION
**Pull request by marmarek**
@adrelanos take a look if no other changes are needed. I've changed only:
 - 15 -> 16
 - buster -> bullseye

### CODE REVIEW

**Comment by adrelanos** [comment]
Looks great!

**Comment by mfc** [comment]
thanks so much for writing out the names without abbreviations. you want to close https://github.com/QubesOS/qubes-issues/issues/1778 ?

**Comment by adrelanos** [comment]
> thanks so much for writing out the names without abbreviations. you want to close [QubesOS/qubes-issues#1778](https://github.com/QubesOS/qubes-issues/issues/1778) ?

Nothing related to that changed in this PR. [QubesOS/qubes-issues#1778](https://github.com/QubesOS/qubes-issues/issues/1778) will still apply as reported.

**Comment by mfc** [comment]
ah ok i misread the commit. whenever the whonix 16 templates are getting made would be a great opportunity to apply #1778

**Comment by adrelanos** [comment]
In my understanding permission to go ahead in https://github.com/QubesOS/qubes-issues/issues/1778 has not been granted. If I am interpreting that wrong, please update https://github.com/QubesOS/qubes-issues/issues/1778.

**Pull request merged**
